### ISSUE TITLE
Unable to pull image when running in AWS ECS Fargate

### ISSUE THREAD

**Issue by vshulgin** [deepfence/terraform-aws-cloud-scanner#13]
Error is as follow:
```
CannotPullContainerError: pull image manifest has been retried 5 time(s): failed to resolve ref quay.io/deepfenceio/cloud-scanner:latest: failed to do request: Head "https://quay.io/v2/deepfenceio/cloud-scanner/manifests/latest": dial tcp 3.210.148.47:443: i/o timeout
```
We tried to run task in:
- private subnet with default route to  NAT in public subnet and IGW in public subnet
- public subnet with default route to IGW and public IP auto-assigned

**Comment by shyam-dev** [comment]
Will be tracked here - https://github.com/deepfence/ThreatMapper/issues/1097
